version: "3"
networks:
  store-network:
volumes:
  store-postgresql:
    driver: local
services:
  postgresql:
    image: postgres:12.4
    container_name: store-postgresql
    volumes:
      - store-postgresql:/var/lib/postgresql/data/
    networks:
      - store-network
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo31234
    ports:
      - 5432:5432