server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/store
    username: demo
    password: demo31234
  jpa:
    properties:
      hibernate:
        hikari:
          auto_commit: false
        default_schema: store_data
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  profiles:
    active:
      - prod